# Generated by Django 4.2.6 on 2023-11-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_app', '0007_saved_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
